import { fileURLToPath } from 'node:url'

export const sites = [
  {
    name: 'Deudores BCRA',
    description: 'Central de Deudores',
    subdomain: 'deudores.bcra',
    baseDir: '/sites/bcra/deudores',
    specUrl: fileURLToPath(new URL('../assets/deudores.bcra.openapi.json', import.meta.url)),
    tags: ['BCRA'],
  },
  {
    name: 'Cheques BCRA',
    description: 'Cheques denunciados',
    subdomain: 'cheques.bcra',
    baseDir: '/sites/bcra/cheques',
    specUrl: fileURLToPath(new URL('../assets/cheques.bcra.openapi.json', import.meta.url)),
    tags: ['BCRA'],
  },
  {
    name: 'Principales Variables BCRA',
    description: 'Estadísticas Monetarias / Principales Variables',
    subdomain: 'principales-variables.bcra',
    baseDir: '/sites/bcra/principales-variables',
    specUrl: fileURLToPath(new URL('../assets/principales-variables.bcra.openapi.json', import.meta.url)),
    tags: ['BCRA'],
    autogenerate: false,
  },
  {
    name: 'Estadisticas Cambiarias',
    description: 'Estadísticas Cambiarias',
    subdomain: 'estadisticas-cambiarias.bcra',
    baseDir: '/sites/bcra/estadisticas-cambiarias',
    specUrl: fileURLToPath(new URL('../assets/estadisticas-cambiarias.bcra.openapi.json', import.meta.url)),
    tags: ['BCRA'],
    autogenerate: false,
  },
  {
    name: 'SOFSE Trenes',
    description: 'API de Trenes de SOFSE',
    subdomain: 'trenes.sofse',
    baseDir: '/sites/sofse/trenes',
    specUrl: fileURLToPath(new URL('../assets/trenes.sofse.openapi.json', import.meta.url)),
    tags: ['Transporte'],
  },
  {
    name: 'Georef',
    description: 'API del Servicio de Normalización de Datos Geográficos de Argentina',
    subdomain: 'georef.argentina',
    baseDir: '/sites/argentina/georef',
    specUrl: fileURLToPath(new URL('../assets/georef.argentina.openapi.json', import.meta.url)),
    tags: ['Argentina'],
    autogenerate: false,
  },
  {
    name: 'Series de Tiempo',
    description: 'API de Series de Tiempo de la República Argentina',
    subdomain: 'series-tiempo.argentina',
    baseDir: '/sites/argentina/series-tiempo',
    specUrl: fileURLToPath(new URL('../assets/series-tiempo.argentina.openapi.json', import.meta.url)),
    tags: ['Argentina'],
    autogenerate: false,
  },
  {
    name: 'Resultados Electorales',
    description: 'API de Resultados Electorales de la República Argentina',
    subdomain: 'resultados-electorales.argentina',
    baseDir: '/sites/argentina/resultados-electorales',
    specUrl: fileURLToPath(new URL('../assets/resultados-electorales.argentina.openapi.json', import.meta.url)),
    tags: ['Argentina'],
    autogenerate: false,
  },
  {
    name: 'Presupuesto Abierto',
    description: 'API de Presupuesto Abierto de la República Argentina',
    subdomain: 'presupuesto-abierto.argentina',
    baseDir: '/sites/argentina/presupuesto-abierto',
    specUrl: fileURLToPath(new URL('../assets/presupuesto-abierto.argentina.openapi.json', import.meta.url)),
    tags: ['Argentina'],
    autogenerate: false,
  },
  {
    name: 'Ministerio de Cultura',
    description: 'API del Ministerio de Cultura de la República Argentina',
    subdomain: 'cultura.argentina',
    baseDir: '/sites/argentina/cultura',
    specUrl: fileURLToPath(new URL('../assets/cultura.argentina.openapi.json', import.meta.url)),
    tags: ['Argentina'],
    autogenerate: false,
  },
]
